openapi: 3.0.3
info:
  title: Blog API Documentation
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Local Development Server
tags:
  - name: csrf-protection
    description: CSRF攻撃対策のAPI
paths:
  # GET /csrf-cookie
  /csrf-cookie:
    get:
      tags: [csrf-protection]
      operationId: getCsrfCookie
      summary: CSRF Cookieの取得
      description: |
        リクエストに成功すると、204 No Content のレスポンスが返ります。
        このレスポンスの Set-Cookie ヘッダーに XSRF-TOKEN が含まれています。
        POSTリクエストを実行するときは、受け取った XSRF-TOKEN の値を X-XSRF-TOKEN ヘッダーに設定する必要があります。
        XSRF-TOKENの値はPOSTリクエストのたびに取得し直す必要はなく、同じ値を何度も使うことができます。
      responses:
        '204':
          description: No Content
          headers:
            Set-Cookie:
              description: CSRF対策に利用する XSRF-TOKEN という Cookie が含まれています。
              schema:
                type: string
                example: XSRF-TOKEN=ZmQzNGNhY2EtOWRjOC00YzU2LTkxZWItYTEyMThmMTU1ZjY2
          content:
            {}
        '500':
          $ref: "#/components/responses/InternalServerErrorResponse"

components:
  schemas:
    InternalServerError:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
          default: 500
        detail:
          type: string
        instance:
          type: string
          format: uri

  responses:
    InternalServerErrorResponse:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/InternalServerError"